apiVersion: v1
kind: Service
metadata:
  name: django-k8s-service
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    app: django-k8s
